apiVersion: v1
kind: Pod
metadata:
    name: kubia-mac
    labels:
        creation_method: manual
        env: prod
spec:
    nodeSelector:
        mac: "true"
    containers:
    - image: luksa/kubia
      name: kubia
      ports:
      - containerPort: 8080
        protocol: TCP
